# Generated by Django 3.1 on 2020-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0005_aboutus_aboutuscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscategory',
            name='image',
            field=models.FileField(blank=True, upload_to='about/'),
        ),
    ]
