# Generated by Django 3.1 on 2020-08-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0009_plains_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainsimages',
            name='image',
            field=models.ImageField(upload_to='plains/'),
        ),
    ]
