# Generated by Django 3.1 on 2020-08-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0012_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
