# Generated by Django 3.1 on 2020-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0014_auto_20200825_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
