# Generated by Django 3.1 on 2020-08-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0015_auto_20200825_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_hy',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_hy',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
    ]
