# Generated by Django 3.1 on 2020-08-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0016_auto_20200829_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text_hy',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text_ru',
        ),
    ]
