# Generated by Django 3.0.8 on 2020-09-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0018_auto_20200829_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='sphere_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umcorapp.PlainsCategory'),
        ),
        migrations.AddField(
            model_name='donate',
            name='sphere_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umcorapp.PlainsCategory'),
        ),
        migrations.AddField(
            model_name='donate',
            name='sphere_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umcorapp.PlainsCategory'),
        ),
        migrations.AddField(
            model_name='donate',
            name='target_group_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='target_group_hy',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='target_group_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plains',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='plains',
            name='name_hy',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='plains',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='plains',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plains',
            name='text_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plains',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
