# Generated by Django 3.1.1 on 2020-09-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umcorapp', '0019_auto_20200906_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='sphere_ru',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='target_group_ru',
        ),
        migrations.RemoveField(
            model_name='maincontent',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='plains',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='plains',
            name='text_ru',
        ),
    ]
